// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdhXLAMv-Ws28T1yqJKQMrne-GUHL6mEI',
    appId: '1:990716361936:web:6d7249bcb023f3fa52b2d5',
    messagingSenderId: '990716361936',
    projectId: 'flutter-projects-94ac5',
    authDomain: 'flutter-projects-94ac5.firebaseapp.com',
    databaseURL: 'https://flutter-projects-94ac5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-projects-94ac5.appspot.com',
    measurementId: 'G-WKB4M2SF5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHpsuaKHUvBZWbhJUbY53ErBWoUGVgX0k',
    appId: '1:990716361936:android:aabf332dcc294c5752b2d5',
    messagingSenderId: '990716361936',
    projectId: 'flutter-projects-94ac5',
    databaseURL: 'https://flutter-projects-94ac5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-projects-94ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbACa3E_kYCIO0OS66c9r7LdOcGJDPflU',
    appId: '1:990716361936:ios:c3b00b3103353f4e52b2d5',
    messagingSenderId: '990716361936',
    projectId: 'flutter-projects-94ac5',
    databaseURL: 'https://flutter-projects-94ac5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-projects-94ac5.appspot.com',
    iosBundleId: 'com.example.eShopDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbACa3E_kYCIO0OS66c9r7LdOcGJDPflU',
    appId: '1:990716361936:ios:c3b00b3103353f4e52b2d5',
    messagingSenderId: '990716361936',
    projectId: 'flutter-projects-94ac5',
    databaseURL: 'https://flutter-projects-94ac5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-projects-94ac5.appspot.com',
    iosBundleId: 'com.example.eShopDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdhXLAMv-Ws28T1yqJKQMrne-GUHL6mEI',
    appId: '1:990716361936:web:aee55a0c132e4c9752b2d5',
    messagingSenderId: '990716361936',
    projectId: 'flutter-projects-94ac5',
    authDomain: 'flutter-projects-94ac5.firebaseapp.com',
    databaseURL: 'https://flutter-projects-94ac5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-projects-94ac5.appspot.com',
    measurementId: 'G-B0YTZC3D2Z',
  );
}
